### PR TITLE
Appveyor fix, run tests for netstandard1.6 via netcoreapp1.1

### PR DESCRIPTION
**Pull request by jindraivanek**
Following https://github.com/jack-pappas/ExtCore/issues/35#issuecomment-345956400, I found issue of appveyor being red is because netstandard1.6 tests is not actually working.

This add testing of netstandard1.6 on .NET Core 1.1 to both appveyor and travis.

### CODE REVIEW

**Comment by wallymathieu** [comment]
Could this be merged @jack-pappas ?

**Comment by vasily-kirichenko** [comment]
@wallymathieu I have rights to merge this, but I don't have ones to publish NuGet package, so, I'm not sure I should merge it...

**Comment by wallymathieu** [comment]
I understand. Though this PR deals mostly with build failure and doesn't add or remove any feature.

**Comment by vasily-kirichenko** [comment]
Sorry, I thought it’s the Result PR :)

**Pull request merged**
