### PR TITLE
WIP Move to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
Open issues:

* [ ] Seq tests fails because no functions are visible except `ofAsyncSeq`:

image

image

This is an interesting issue: `Seq` module is defined twice in `ExtCore.Collections` namespace, once with ModuleSuffix attribute and once - without it:

* In `Collections.Seq.fs`

```fsharp
/// Additional functional operators on sequences.
[<RequireQualifiedAccess; CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module ExtCore.Collections.Seq
```
* In `Collections.AsyncSeq.fs`

```fsharp
namespace ExtCore.Collections
...
module Seq =
    /// <summary>
    /// Converts asynchronous sequence to a synchronous blocking sequence.
    /// The elements of the asynchronous sequence are consumed lazily.
    /// </summary>
    /// <param name="input"></param>
    /// <returns></returns>
    [<CompiledName("FromAsyncSeq")>]
    let ofAsyncSeq (input : AsyncSeq<'T>) : seq<'T> =
        AsyncSeq.toSeq input
```
I've commented out `ofAsyncSeq` and it's fixed the compilation. I suspect it's a regression in F# 4.1

/cc @dsyme

- [x] All tests pass except single one:

```fsharp
Tests.ExtCore.Control.Collections.Async+Seq+Parallel.batch

  Expected is <System.Int32[10]>, actual is <System.Int32[24]>
  Values differ at index [3]
  Expected: 16
  But was:  4

   at Tests.ExtCore.Control.Collections.Async.Seq.Parallel.batch() in E:\github\ExtCore\ExtCore.Tests\ControlCollections.Async.fs:line 1092
```
- I removed the nuspec as it's obsolete now
- I removed all portable profiles as they are obsolete now. However, I know literally nothing about portable stuff. Have they actually dead now and forever? /cc @enricosada 
- Running `dotnet pack` in `ExtCore` folder successfully creates NuGet package:
```
> dotnet pack
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  ExtCore -> E:\github\ExtCore\ExtCore\bin\Debug\net45\ExtCore.dll
  ExtCore -> E:\github\ExtCore\ExtCore\bin\Debug\netstandard2.0\ExtCore.dll
  Successfully created package 'E:\github\ExtCore\ExtCore\bin\Debug\ExtCore.0.8.47.nupkg'.
```

I'd like to hear what do you guys thought of all this. Is this the right direction? Have I done everything properly? Thanks!

### CODE REVIEW

**Comment by jack-pappas** [comment]
This is great! Thanks Vasily! Let me take a look over it today and tomorrow.

The one test that's failing is a known bug in the implementation of the ``Async,Seq.Parallel.batch`` function -- see #15.

/cc @7sharp9 @jindraivanek

**Comment by vasily-kirichenko** [comment]
About the issue with duplicated `Seq` module, see https://github.com/Microsoft/visualfsharp/issues/3565

**Comment by vasily-kirichenko** [comment]
Apparently NUnit Core test adapter does not support 2.0 https://github.com/nunit/dotnet-test-nunit/issues/122

**Comment by vasily-kirichenko** [comment]
AppVeyor tries to build it with msbuild 12 and fails.

**Comment by vasily-kirichenko** [comment]
It installs .net core 2.0, builds the solution and run the tests on Core. All on Windows. I don't know what to do next.

**Comment by jack-pappas** [comment]
Thanks Vasily! I've merged your changes. I think I need to make a few more tweaks to the build process, but I'll work on it today. (A few things in ExtCore use F# features restricted to FSharp.Core and require ``fsc-proto`` to build. It's possible to build ExtCore with a regular F# compiler but those things are excluded with a preprocessor macro.)

**Comment by vasily-kirichenko** [comment]
Thanks!

**Pull request merged**
